Fixed oops

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,44 +1,22 @@
 #!/bin/bash
-#install script for alpine-backup
-#(C) Copyright 2010 Nicholas Paun. All Rights Reserved.
+#MintPhoto installer
+#(C) Copyright 2009-2010 Nicholas Paun. All Rights Reserved.
 
-$conf = '/etc/backup.d'
-$man = '/usr/share/man/man.8'
-$lib = '/usr/lib/alpine-backup'
-$code = '/usr/sbin'
+INSTALLDIR="/srv/www/htdocs/mint4c/" #Directory to copy MintPhoto files
+TOOLDIR="/usr/local/bin/" #Directory to copy tools
 
-echo "*** Installing alpine-backup 0.60 ***"
-
-if [[ $check = "1" ]]; then
- $latest = wget -O - http://iceberg.dnsalias.net/softtrack/alp
- if [[ $version != $latest]]; then
-  echo "This is not the latest version. (You have $version; latest is $latest)"
- fi
-fi 
-
-$isphp = `which php`
-if [[ $isphp != 0 ]]; then
- echo "Cannot find php. Exiting"
+which php &> /dev/null
+if [[ $? != 0 ]]; then
+ echo "PHP not found"
  exit 1
 fi
 
-echo "Copying code to $code"
-cp alpine-backup $code/alpine-backup
-chmod u+x $code/alpine-backup
-ln -s alpine-backup alp #adding symlink
-
-if [[ -d "/etc/backup.d" ]]; then
- echo "Preserving old configuration files"
-else
- echo "Copying example configuration files"
- rsync -av conf/ $conf
+which jhead &> /dev/null
+if [[ $? != 0 ]]; then
+ echo "jhead not found"
 fi
 
+rsync -av ./ $INSTALLDIR
+rsync -av ./tools/ $TOOLDIR
 
-echo "Copying lib files"
-rsync -av lib/ $lib
-
-#echo "Copying man pages"
-#cp man/ /usr/share/man/man.8
-
-echo "OK. Hope the install works!"
+exit 0
